---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-static-site
  namespace: argocd
  labels:
    crossplane.atrakic.github.io: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/atrakic/go-static-site
    targetRevision: HEAD
    path: charts/go-static-site
  helm:
    #valueFiles:
    #  - values.yaml
    parameters:
      - name: image.tag
        value: main
      #- name: storageclass
      #  value: {{ .Values.storageClass }}
  destination:
    namespace: go-static-site
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
      syncOptions:
        - CreateNamespace=true
